### PR TITLE
adding the LoginFail_EmptyInputTest.php

### PR DESCRIPTION
**Pull request by tohungsze**
This is an integration test that verifies end-to-end scenario for a failed login due to missing input.

### CODE REVIEW

**Comment by JwTurner** [comment]
Where does this comment show up?

**Comment by JwTurner** [comment]
Undo-ing previous

**Review by eaglet3d — CHANGES_REQUESTED** [review]
Accept all except Jim's change.

**Review by JwTurner — DISMISSED** [review]
what Ralph said

**Review by eaglet3d — APPROVED** [review]

**Pull request merged**
